Data Science I Homework 6
================
Ruicheng Yang

# Question 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.1     ✔ stringr   1.5.2
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(p8105.datasets)
library(broom)

homicide_data <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv") 
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
homicide_data <- homicide_data |>
  mutate( city_state = paste(city, state, sep = ", "),
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `victim_age = as.numeric(victim_age)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
homicide_data_clean <- homicide_data |>
  filter(!(city_state == "Dallas, TX" | city_state == "Phoenix, AZ" | city_state == "Kansas City, MO" |
             city_state == "Tulsa, AL")) |>
  filter(victim_race == "White" | victim_race == "Black")

baltimore_df <- homicide_data_clean |>
  filter(city_state == "Baltimore, MD")

baltimore_fit <- glm(
  solved ~ victim_age + victim_sex + victim_race,
  data = baltimore_df,
  family = binomial
)

baltimore_tidy <- broom::tidy(baltimore_fit, conf.int = TRUE, exp = TRUE)

baltimore_OR_male <- baltimore_tidy |>
  filter(term == "victim_sexMale") |>
  select(term, estimate, conf.low, conf.high)

baltimore_OR_male
```

    ## # A tibble: 1 × 4
    ##   term           estimate conf.low conf.high
    ##   <chr>             <dbl>    <dbl>     <dbl>
    ## 1 victim_sexMale    0.426    0.324     0.558

``` r
city_results <- homicide_data_clean |>
  nest(data = -city_state) |>
  mutate(fit = map(data, ~ glm(
      solved ~ victim_age + victim_sex + victim_race,
      data = .x, family = binomial
    )),
    tidy = map(fit, ~ broom::tidy(.x, conf.int = TRUE, exp = TRUE))
  ) |> unnest(tidy) |>
  filter(term == "victim_sexMale") |>
  select(city_state, estimate, conf.low, conf.high)
```

    ## Warning: There were 43 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `tidy = map(fit, ~broom::tidy(.x, conf.int = TRUE, exp =
    ##   TRUE))`.
    ## Caused by warning:
    ## ! glm.fit: fitted probabilities numerically 0 or 1 occurred
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 42 remaining warnings.

``` r
ggplot(city_results,
       aes(x = estimate, y = city_state)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "orange") +
  labs(title = "Adjusted Odds Ratio of Solved Homicides vs City and State",
       x = "Adjusted Odds Ratio",
       y = "City and State")
```

    ## Warning: `geom_errobarh()` was deprecated in ggplot2 4.0.0.
    ## ℹ Please use the `orientation` argument of `geom_errorbar()` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

    ## `height` was translated to `width`.

![](p8105_hw6_ry2539_files/figure-gfm/unnamed-chunk-1-1.png)<!-- -->

For the city of Baltimore, Maryland, the odds ratio of solving homicides
for victims of male sex ranges from 0.324 to 0.558 with 95 percent
confidence compared to victims of female sex. This suggests that male
victims’ homicide cases are less likely to be solved compared to female
victims.

This also seems to hold true for many other cities across the United
States. Cities like Chicago and New York have confidence intervals not
including an odds ratio of 1. However, cities like Albuquerque, New
Mexico have a confidence interval that cover odds ratios much higher
than 1, suggesting the possibility that solving homicides for male
victims is higher than female victims.

# Question 2

``` r
data("weather_df")
set.seed(1)

ideal_model <- tmax ~ tmin + prcp

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps <-
  tibble(b = 1:5000) |>
  mutate(
    boot_sample = map(b, \(i) boot_sample(df = weather_df))
  )

bootstrap_results <- boot_straps |> 
  mutate(
    models = map(boot_sample, \(df) lm(ideal_model, data = df) ),
    r2 = map(models, ~ summary(.x)$r.squared),
    results = map(models, broom::tidy)) |> 
  select(-boot_sample, -models) |> 
  unnest(results)

bootstrap_results_2 <- bootstrap_results |> group_by(b) |> 
  summarize(ratio = estimate[term == "tmin"]/estimate[term == "prcp"])

bootstrap_results |>
  ggplot(aes(x = as.numeric(r2))) +
  geom_histogram() +
  labs(title = "Distribution of R-squared",
       x = "R-squared",
       y = "Count")
```

    ## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.

![](p8105_hw6_ry2539_files/figure-gfm/aisle_total-1.png)<!-- -->

``` r
bootstrap_results_2 |>
  ggplot(aes(x = ratio)) +
  geom_histogram() +
  labs(title = "Distribution of β1 / β2",
       x = "β1 / β2",
       y = "Count")
```

    ## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.

![](p8105_hw6_ry2539_files/figure-gfm/aisle_total-2.png)<!-- -->

``` r
bootstrap_results |>
  summarize(
    ci_lower = quantile(as.numeric(r2), 0.025), 
    ci_upper = quantile(as.numeric(r2), 0.975))
```

    ## # A tibble: 1 × 2
    ##   ci_lower ci_upper
    ##      <dbl>    <dbl>
    ## 1    0.934    0.947

``` r
bootstrap_results_2 |> summarize(
  ci_lower = quantile(ratio, 0.025), 
  ci_upper = quantile(ratio, 0.975))
```

    ## # A tibble: 1 × 2
    ##   ci_lower ci_upper
    ##      <dbl>    <dbl>
    ## 1    -280.    -126.

The distribution of both our parameter ratios and R-squared values of
our distributions are approximately normal. For our model, the true
R-squared values ranges from 0.934 to 0.947 at 95 percent confidence,
suggesting a good fit. We are also 95 percent confident the true value
of the ratio of the two parameters lies between -249.7 to -125.7.
